### PR TITLE
reduce nginx log level from notice to warn

### PR DESCRIPTION
**Pull request by KonradHoeffner**
Part of <https://github.com/Onto-Med/top-deployment/issues/44>.

### CODE REVIEW

**Review by ChristophB — APPROVED** [review]
Just an idea: There is already an [nginx.conf](https://github.com/Onto-Med/top-frontend/blob/master/nginx.conf) file that is copied into the Docker image. Perhaps we could set the desired log levels there instead of using `sed`?

**Comment by KonradHoeffner** [comment]
There are two config files at play here:

`/etc/nginx/nginx.conf` is the default configuration and contains configuration of the nginx server.

`nginx.conf` from the base path of this repository contains configuration of the specific web app and is copied into the `/etc/nginx/conf.d/` directory, which is included from a statement of `/etc/nginx/nginx.conf`: `include /etc/nginx/conf.d/*.conf;`.

## /etc/nginx/nginx.conf

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```

I don't know if it is possible and a better solution to merge those two or if overriding the error_log statement from within the nginx.conf from this repository works as I already tried overwriting it using an env variable which didn't work, so I am not sure if the changes are worth it to try that but feel free if you want.

**Comment by ChristophB** [comment]
The [Nginx documentation](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/) is a bit confusing here.

> The default setting of the error log works globally. To override it, place the [error_log](https://nginx.org/en/docs/ngx_core_module.html#error_log) directive in the main (top-level) configuration context.

> However, if several error_log directives are specified on the same level, the message are written to all specified logs.

I am not sure if `error_log` can be overridden. I will try it tomorrow and if it works, I will create another PR.

**Comment by KonradHoeffner** [comment]
> I am not sure if `error_log` can be overridden (maybe the top level is an exception?). I will try it tomorrow and if it works, I will create another PR.

Good luck! Maybe this StackOverflow post can help you: <https://unix.stackexchange.com/questions/769346/how-to-suppress-nginx-worker-process-notices/771151#771151> at least that shows what I tried to overwrite it which didn't work :-)

**Comment by KonradHoeffner** [comment]
P.S.: Or we just switch to Caddie :-)

**Comment by ChristophB** [comment]
> P.S.: Or we just switch to Caddy :-)

As discussed recently, this would be a nice (or even better) option. But I lack the Caddy knowledge.

**Pull request merged**
