### PR TITLE
Add requirements

### PR DESCRIPTION
**Pull request by KonradHoeffner**

### CODE REVIEW

**Comment by ChristophB** [comment]
We could mention the devcontainer configuration in `.devcontainer`. npm, Yarn and Quasar CLI are included there as well.

**Comment by KonradHoeffner** [comment]
> It says: 'The npm package `@onto-med/top-api` is currently located in a private GitHub Packages registry, thus requires authentication.' The package is public now, but we need to check if authentication is required for GitHub JavaScript Package Manager.

Did you change it today?
Because when I tried it this morning, I kept getting errors until I got the authentication right, but then I rebooted, deleted the node_modules folder and renamed .npmrc for testing, and now it still works.

**Comment by ChristophB** [comment]
> Did you change it today? Because when I tried it this morning, I kept getting errors until I got the authentication right, but then I rebooted, deleted the node_modules folder and renamed .npmrc for testing, and now it still works.

No, I haven't changed anything. Will have a look tomorrow.

**Comment by ChristophB** [comment]
> You need an access token to publish, **install**, and delete private, internal, and public packages.

And accessing the package URL directly results in the following response:

```json
{"error":"authentication token not provided"}
```

So the token-based authentication is definitely required.

**Review by ChristophB — APPROVED** [review]

**Pull request merged**
