### PR TITLE
Enable eslint cache to speed up `yarn lint`

### PR DESCRIPTION
**Pull request by ChristophB**
`yarn lint` will automatically use ESLint cache and store it to `node_modules/.cache/eslint-webpack-plugin/.eslintcache`.

### CODE REVIEW

**Comment by KonradHoeffner** [comment]
Couldn't test it in this repository due to #340 but I rebased a new branch in my fork on this Pr and it is indeed much faster now. However I get the following error, do you get this too?

```
top-frontend$ yarn lint                                                                                                                                  test
yarn run v1.22.21
$ eslint --cache --cache-location node_modules/.cache/eslint-webpack-plugin/.eslintcache --ext .js,.ts,.vue ./

/home/konrad/projekte/top/modules/top-frontend/quasar.conf.js
  12:7  error  Unsafe assignment of an `any` value  @typescript-eslint/no-unsafe-assignment

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```

**Comment by ChristophB** [comment]
> However I get the following error, do you get this too?
Yes, that somehow slipped through.

**Comment by ChristophB** [comment]
Somehow I cannot reproduce it anymore after rebuilding my dev environment.

**Comment by KonradHoeffner** [comment]
Maybe it only occurs with specific Node versions? My `node --version` is 21.6.2.

**Comment by ChristophB** [comment]
> Maybe it only occurs with specific Node versions? My `node --version` is 21.6.2.

I am also on 21.6.2

**Review by KonradHoeffner — APPROVED** [review]

**Comment by KonradHoeffner** [comment]
In the Dockerfile, `yarn global add @quasar/cli` is before the arg statement and on my local machine outside of Docker, that statement generates the error, so maybe the environment variable isn't allowed to be set before this step?

**Comment by ChristophB** [comment]
> In the Dockerfile, `yarn global add @quasar/cli` is before the arg statement and on my local machine outside of Docker, that statement generates the error, so maybe the environment variable isn't allowed to be set before this step?

Are you referring to https://github.com/Onto-Med/top-frontend/issues/340?

**Comment by KonradHoeffner** [comment]
I'm trying it at another machine so that I get a separated view of the two issues.

**Comment by ChristophB** [comment]
I don't think the order of these lines is important, because at this stage no `.npmrc` has been copied into the image.

**Pull request merged**
